gcc : improve system detection
alisw/alidist pull request #2747
Opened 2021-01-09 10:23 UTC by aphecetche

Depending on how gcc was installed on the system the cc link (to gcc) might
not exist at all. But the CC environment variable might, so test that
too.

For the record, I've encountered the situation on a CentOS7 installation where gcc is installed via Spack.

2021-01-09 12:26 UTC, mfasDa commented
I suspect I ran into a similar issue on Ubuntu 18.04, because also on that system with fresh build recipes aliBuild is building gcc though gcc-7.5.0 is installed, which should be OK (for the moment) for AliPhysics and O2.

2021-04-27 11:53 UTC, ktf commented
I think we should simply use `c99`, which is required to be present by the standard.

2021-04-27 14:50 UTC, ktf requested changes
I switched to use c99 in the 10.2 PR. Would that be ok?

2021-04-30 08:54 UTC, ktf commented
Closing this to avoid rebuilding GCC in the CI. Please let me know if c99 is not ok.

2021-04-30 08:54 UTC, closed without merging