Set O2 options in dataflow defaults
alisw/alidist pull request #2850
Opened 2021-02-18 08:42 UTC by awegrzyn

@ktf I think we can safely pass vars from `defaults` instead of `O2-customization` as I don't see a use-case that someone wants to enable it. Are these vars gonna be picked up?

2021-02-18 08:45 UTC, vascobarroso approved these changes

2021-02-18 10:02 UTC, ktf commented
Changing defaults will rebuild everything. Apart from that, there is no difference.

2021-02-18 10:03 UTC, ktf commented on defaults-o2-dataflow.sh
> +  ENABLE_UPGRADES: "OFF" # Disable detector upgrades in O2
This one needs to be done in O2-customizations which will have precedence.

2021-02-18 10:04 UTC, ktf commented
Actually, no this will not work the moment we override them in o2-customization. What you need to do is to override o2-customization itself from the default.

2021-02-18 10:06 UTC, ktf requested changes
You should override o2-customization in defaults-o2-dataflow.sh and change the variables there.

2021-02-18 10:07 UTC, ktf commented
See #2853

2021-02-18 10:18 UTC, awegrzyn commented
> Changing defaults will rebuild everything. Apart from that, there is no difference.

Well, as we're overwriting it in the defaults so I guess the full rebuilt is inevitable

2021-02-22 13:25 UTC, merged

2021-02-23 11:28 UTC, awegrzyn commented
@ktf This does not work as expected, do we need any changes to O2 recipe? By default CMake does not pick up env vars.

2021-02-23 11:41 UTC, ktf commented
you probably need something like `-DBUILD_ANALYSIS=$BUILD_ANALYSIS`. For upgrades it should already be there.

2021-02-23 12:03 UTC, awegrzyn commented
Well, not really: https://github.com/alisw/alidist/blob/ba9b61c24eac62c295ca5ed249ac02ba0c1d3366/o2.sh#L190
If `ENABLE_UPGRADES` variable is set, it will be always overwritten by `-DENABLE_UPGRADES=ON`.