Added missing compilation flag -lpthread and module file creation.
alisw/alidist pull request #3535
Opened 2021-11-09 11:25 UTC by jan-busa

When building CLHEP with --no-system build on current C++ Toolset (10.2), phtread was missing to sucessfully build the CLHEP. Also module creation was added to be able to link to CLHEP from other projects.

2021-11-09 13:47 UTC, ktf requested changes
You should probably factor out the CXXFLAGS change (which requires modifications) from the rest (which is probably good to go already as-is).

2021-11-10 06:42 UTC, jan-busa commented on clhep.sh
> +CXXFLAGS="${CXXFLAGS} -lpthread"
Thank you for noting the upsream. I was able to override the problem by using directly latest CLHEP from the original repo:
```
overrides:
  CLHEP:
    version: v2.4.5.1
    tag: CLHEP_2_4_5_1
    source: https://gitlab.cern.ch/CLHEP/CLHEP.git
```
Obviously, in the latest version of CLHEP the problem with pthread has been fixed.
I did remove the CXXFLAGS and left only missing dependencies of CMake and build of modulefile.
Concerning the architecture question, I am doing a minimal dependencies build inside CentOS 7 toolbox.

2021-11-10 10:27 UTC, ktf approved these changes

2021-11-10 10:28 UTC, ktf commented on clhep.sh
> +CXXFLAGS="${CXXFLAGS} -lpthread"
I think we can try to bump our own CLHEP as well. @sawenzel do you think that will create troubles to Geant4?

2021-11-23 09:06 UTC, merged