Bump Root to v6-28-02
alisw/alidist pull request #4920
Opened 2023-03-22 08:01 UTC by pzhristov

2023-03-22 14:56 UTC, sawenzel commented on root.sh
> -source: https://github.com/alisw/root.git
I think that we will loose a couple of commits in our fork which have not been backported to root. This should not be done.

2023-03-22 14:57 UTC, sawenzel requested changes
I think that we will loose a couple of commits in our fork which have not been backported to root. This should not be done.

2023-03-22 18:54 UTC, ktf approved these changes

2023-03-23 07:50 UTC, merged

2023-03-23 07:52 UTC, ktf commented
Merging this to see if we spot other issues in production. We can have a alice1 tag with the missing treatment of ROOT_LDSYSPATH. Are we sure this is still relevant, though?

2023-03-23 07:54 UTC, sawenzel commented
> Merging this to see if we spot other issues in production. We can have a alice1 tag with the missing treatment of ROOT_LDSYSPATH. Are we sure this is still relevant, though?

Yes, I have no reason to believe otherwise.