Add libuv dependency to libwebsockets
alisw/alidist pull request #5200
Opened 2023-11-02 14:10 UTC by yuw726

Enable libuv support in JAliEn-ROOT by adding libuv as a dependency in libwebsockets recipe

2023-11-02 14:16 UTC, ktf commented on libwebsockets.sh
> +      ${LIBUV_ROOT:+-DLIBUV_INCLUDE_DIRS=$LIBUV_ROOT/include}       \
Please, use `${LIBUV_REVISION:...}` rather than `${LIBUV_ROOT:...}`

2023-11-02 14:16 UTC, ktf requested changes
See inline.

2023-11-02 14:37 UTC, ktf approved these changes

2023-11-03 11:14 UTC, yuw726 commented
build/alidist/O2Suite/o2/macOS check fails because libwebsockets cannot link to libuv:
```
Searching for OpenSSL executable and dlls
OpenSSL executable: /opt/homebrew/opt/openssl@3/bin/openssl
 GENCERTS = 0
libuv include dir: /Volumes/build/alice-ci-workdir/alidist-o2/sw/osx_arm64/libuv/v1.40.0-local1/include
libuv libraries: /Volumes/build/alice-ci-workdir/alidist-o2/sw/osx_arm64/libuv/v1.40.0-local1/lib
-- Looking for uv-version.h
-- Looking for uv-version.h - not found
-- Looking for uv/version.h
-- Looking for uv/version.h - not found
DIR /Volumes/build/alice-ci-workdir/alidist-o2/sw/BUILD/85465dbd00be206b84a2f6b337cfe01c4a99036a/libwebsockets CMP /Volumes/build/alice-ci-workdir/alidist-o2/sw/SOURCES/libwebsockets/v4.3.2/v4.3.2/cmake
-- Configuring done (7.5s)
CMake Warning at lib/CMakeLists.txt:268 (target_link_libraries):
  Target "websockets" requests linking to directory
  "/Volumes/build/alice-ci-workdir/alidist-o2/sw/osx_arm64/libuv/v1.40.0-local1/lib".
  Targets may link only to libraries.  CMake is dropping the item.


-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENSSL_ROOT_DIR

```

The error comes from https://github.com/warmcat/libwebsockets/blob/v4.3.2/lib/CMakeLists.txt#L268, where `target_link_libraries` tries to link to the libuv lib path instead of the library.

It is strange that it does work on other OSs.

2023-11-16 10:18 UTC, ktf commented
As discussed, the problem is that libwebsocket is an archive (.a) library, so it does not bring in automatically the transitive closure of its dependencies. Given in any case you use it, I would explicitly find LibUV and add a dependency for `LibUV::LibUV` in your `CMakeList.txt`.

2023-12-07 08:53 UTC, yuw726 commented
Hi @ktf, will you have an opportunity to test these recipes together with `add-libuv-support` branch of https://gitlab.cern.ch/jalien/jalien-root/ on Hyperloop?

2024-01-15 12:14 UTC, costing approved these changes

2024-01-18 16:46 UTC, zensanp approved these changes

2024-01-25 13:08 UTC, merged