ARM: Bump hdf5, numpy, scipy, Keras/tf and pandas
alisw/alidist pull request #5547
Opened 2024-07-09 12:44 UTC by singiamtel

The CI for ARM is complaining about tensorflow, had to bump some versions. Tested on pip 21.2.3 and Python 3.9.18

@mfasDa do you agree with the changes? (follow-up to #5539)

Closes #5524 and #5525 too

The error:
```
2024-07-09@12:48:57:DEBUG:Python-modules:Python-modules:slc9_aarch64: Collecting Keras==2.7.0
2024-07-09@12:48:57:DEBUG:Python-modules:Python-modules:slc9_aarch64:   Downloading keras-2.7.0-py2.py3-none-any.whl (1.3 MB)
2024-07-09@12:48:57:DEBUG:Python-modules:Python-modules:slc9_aarch64:      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 22.1 MB/s eta 0:00:00
2024-07-09@12:48:57:DEBUG:Python-modules:Python-modules:slc9_aarch64: ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.1 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1)
2024-07-09@12:48:57:DEBUG:Python-modules:Python-modules:slc9_aarch64: ERROR: No matching distribution found for tensorflow==2.7.1
```

2024-07-09 13:59 UTC, mfasDa commented
@singiamtel As discussed in the other PR I am also in favour of bumping to newer versions of sklearn, numpy, pandas, tensorflow and Keras, I just did the minimal changes to get tensorflow back in for older python versions, and leave the aligned version bump to you.

2024-07-09 14:41 UTC, singiamtel commented
For what it's worth, this also bypasses the same problem https://github.com/alisw/alidist/pull/5459

2024-07-19 10:33 UTC, ktf requested changes
This seems to break aligenerators, actually...

2024-07-24 07:09 UTC, ktf commented
@singiamtel Looks like we are missing a -DHDF5_DIR=... or something like that. Could you take a look?

2024-07-24 15:19 UTC, ktf commented
@singiamtel it looks like it's still broken.

2024-07-25 10:53 UTC, ktf commented on hdf5.sh
>    printf "#include <hdf5.h>\n" | cc -xc - -c -o /dev/null
```suggestion
  printf "#include <hdf5.h>\n" | cc -xc - -c -o /dev/null
  env:
    HDF5_DIR: "$HDF5_ROOT"
```

2024-07-25 10:53 UTC, ktf commented on hdf5.sh
>    printf "#include <hdf5.h>\n" | cc -xc - -c -o /dev/null
Actually we need this to compile the python module.

2024-07-25 11:28 UTC, ktf commented on hdf5.sh
> +  env:
```suggestion
env:
```

2024-07-25 20:08 UTC, merged

2024-07-25 20:08 UTC, ktf commented
Errors on ARM are the next issue to support the platform. Merging this.