Update Upcgen recipe
alisw/alidist pull request #5695
Opened 2024-11-21 15:24 UTC by nburmaso

A small change to update recipe to the latest Upcgen version

@pbuehler, please take a look

Cheers,
Nazar

2024-11-26 09:42 UTC, pbuehler approved these changes

2024-11-26 09:45 UTC, pbuehler commented
Hi @ktf, can you please approve this PR?

2024-11-26 12:24 UTC, ktf approved these changes

2024-11-26 12:25 UTC, ktf commented
@pbuehler Can you please add the package to the CODEOWNERS file, adding yourself as responsible for it?

2024-11-26 12:30 UTC, pbuehler commented
Hi @nburmaso please see previous comment by @ktf. Can you please take care?

2024-11-26 13:00 UTC, nburmaso commented
> Hi @nburmaso please see previous comment by @ktf. Can you please take care?

Hi @pbuehler, @ktf,

I have added the line

```
upcgen* @nburmaso @pbuehler
```

but me and Paul have no write access for alidist repository -- is it ok?

2024-11-26 13:57 UTC, ktf commented
I guess it's @alisw/pagmc?

2024-11-26 14:34 UTC, nburmaso commented
> I guess it's @alisw/pagmc?

I have changed owners to @alisw/pagmc and requested membership

2024-11-26 21:09 UTC, ktf requested changes

2024-11-26 21:09 UTC, ktf commented on upcgen.sh
> +cp ./libUpcgenlib.so $INSTALLROOT/lib/.
Indeed, you should add double quotes around the various `$INSTALLROOT/something`.

2024-11-26 21:10 UTC, ktf commented on upcgen.sh
>  #ModuleFile
While you are at it, please use `alibuild-generate-module --lib --bin` as done elsewhere.

2024-11-27 09:45 UTC, nburmaso commented
Hi @ktf, @pbuehler,

I have fixed quotes and module generation, should be ok now.

Cheers,
Nazar

2024-11-27 09:47 UTC, ktf commented on upcgen.sh
>  EoF
```suggestion
```

2024-11-27 09:48 UTC, ktf approved these changes

2024-11-27 09:48 UTC, ktf commented on upcgen.sh
>  #ModuleFile
No need for the custom PATH / LD_LIBRARY_PATH. I removed it.

2024-11-27 09:50 UTC, nburmaso commented on upcgen.sh
>  EoF
Thanks a lot!

2024-11-29 08:17 UTC, jackal1-66 commented
Hi @nburmaso, I see that you have two new tags in the alice fork of upcgen which are not present in the original repository. Did you simply tweak something in the older version to make it compile in our framework? I ask you because in that case there is a guideline on how to choose the tag name: if the new tag is an offspring of [tag-24-06-22](https://github.com/nburmaso/upcgen/releases/tag/tag-24-06-22) only for ALICE use, then it should be called tag-24-06-22-alice1. Let me know if this is the case. If so I would ask you to make the modification before merging. The CI tests are not so useful in this PR because upcgen is not a requirement of O2 or AliGenenerators so it won't be built.

2024-11-29 09:15 UTC, nburmaso commented
> Hi @nburmaso, I see that you have two new tags in the alice fork of upcgen which are not present in the original repository. Did you simply tweak something in the older version to make it compile in our framework? I ask you because in that case there is a guideline on how to choose the tag name: if the new tag is an offspring of [tag-24-06-22](https://github.com/nburmaso/upcgen/releases/tag/tag-24-06-22) only for ALICE use, then it should be called tag-24-06-22-alice1. Let me know if this is the case. If so I would ask you to make the modification before merging. The CI tests are not so useful in this PR because upcgen is not a requirement of O2 or AliGenenerators so it won't be built.

Hi @jackal1-66,

The tag isn't for ALICE-only use. This is my mistake, I should have created the tag in the original repository -- should I do so now or can we continue like this?

Cheers,
Nazar

2024-11-29 09:58 UTC, jackal1-66 commented
We can continue this way, just sync the tags on the original repo.

2024-11-29 18:11 UTC, nburmaso commented
> We can continue this way, just sync the tags on the original repo.

Hi @jackal1-66,

Done :) Could we please merge this PR if it is ok? Also, could you please add me to @alisw/pagmc?

Cheers,
Nazar

2024-12-01 07:50 UTC, sawenzel approved these changes

2024-12-01 07:51 UTC, merged