[OMON-793] Add dependency on kafka and protobuf in Monitoring
alisw/alidist pull request #5712
Opened 2024-12-09 13:38 UTC by Barthelemy

2024-12-09 13:55 UTC, sy-c requested changes
Thanks for this fix. However I'm not sure if it's right to do so (see comment in JIRA).

2024-12-10 08:49 UTC, Barthelemy commented
we can close it for what I am concerned.

2025-01-07 08:35 UTC, ktf commented
Can this be closed?

2025-01-24 11:42 UTC, vascobarroso approved these changes

2025-01-24 12:40 UTC, vascobarroso commented
@sy-c looks like one of the tests is failing, could you have a look ?

2025-01-24 14:53 UTC, sy-c commented
@vascobarroso compile fix released

2025-01-24 14:59 UTC, vascobarroso approved these changes

2025-01-24 17:23 UTC, vascobarroso commented
@ktf errors look unrelated to me. If that's the case, could you merge this ? We need it for early next week. Thanks!

2025-01-24 23:04 UTC, ktf commented
I assume you only need this for the o2-dataflow default? I'd rather not have a dependency on kafka for the general case. If yes, would you mind adding the customisation to the default?

2025-01-27 08:25 UTC, sy-c commented
@ktf I moved librdkafka requires to defaults-o2-dataflow.sh. Is this the way to do it ? It seems to work on my dev setup.
I have not found in other recipes another way to have an "if" confitional on the "defaults" chosen.

2025-01-27 08:27 UTC, ktf commented
Yes, it would need to be moved to the dataflow default. Indeed we could have some "defaults dependent" specification for the dependencies... Let me see how difficult it is.

2025-01-27 08:33 UTC, sy-c commented
Thanks for checking! Optional test like for OS would indeed be nice, but the current solution for today is good enough.

2025-01-27 08:55 UTC, ktf commented
https://github.com/alisw/alibuild/pull/901 will allow you to write:

```yaml
requires:
  libkafka:defaults=o2-dataflow
```

2025-01-27 11:02 UTC, vascobarroso approved these changes

2025-01-27 14:43 UTC, merged

2025-01-27 14:44 UTC, ktf commented
@Barthelemy The issue in QC seems to be a genuine (yet unrelated) problem. Can you please have MCH have a look?